// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/v1/telemetry.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnomalyReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AnomalyScore  float64                `protobuf:"fixed64,3,opt,name=anomaly_score,json=anomalyScore,proto3" json:"anomaly_score,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	HdcVector     []byte                 `protobuf:"bytes,5,opt,name=hdc_vector,json=hdcVector,proto3" json:"hdc_vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnomalyReportRequest) Reset() {
	*x = AnomalyReportRequest{}
	mi := &file_api_proto_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyReportRequest) ProtoMessage() {}

func (x *AnomalyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyReportRequest.ProtoReflect.Descriptor instead.
func (*AnomalyReportRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *AnomalyReportRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AnomalyReportRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AnomalyReportRequest) GetAnomalyScore() float64 {
	if x != nil {
		return x.AnomalyScore
	}
	return 0
}

func (x *AnomalyReportRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AnomalyReportRequest) GetHdcVector() []byte {
	if x != nil {
		return x.HdcVector
	}
	return nil
}

type AnomalyReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnomalyReportResponse) Reset() {
	*x = AnomalyReportResponse{}
	mi := &file_api_proto_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyReportResponse) ProtoMessage() {}

func (x *AnomalyReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyReportResponse.ProtoReflect.Descriptor instead.
func (*AnomalyReportResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *AnomalyReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AnomalyReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_v1_telemetry_proto protoreflect.FileDescriptor

const file_api_proto_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/v1/telemetry.proto\x12\x13cortex.telemetry.v1\"\xa7\x01\n" +
	"\x14AnomalyReportRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12#\n" +
	"\ranomaly_score\x18\x03 \x01(\x01R\fanomalyScore\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"hdc_vector\x18\x05 \x01(\fR\thdcVector\"K\n" +
	"\x15AnomalyReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2z\n" +
	"\x10TelemetryService\x12f\n" +
	"\rReportAnomaly\x12).cortex.telemetry.v1.AnomalyReportRequest\x1a*.cortex.telemetry.v1.AnomalyReportResponseB:Z8github.com/jbraconig/cortex-hdc/api/proto/v1;telemetryv1b\x06proto3"

var (
	file_api_proto_v1_telemetry_proto_rawDescOnce sync.Once
	file_api_proto_v1_telemetry_proto_rawDescData []byte
)

func file_api_proto_v1_telemetry_proto_rawDescGZIP() []byte {
	file_api_proto_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_telemetry_proto_rawDesc), len(file_api_proto_v1_telemetry_proto_rawDesc)))
	})
	return file_api_proto_v1_telemetry_proto_rawDescData
}

var file_api_proto_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_telemetry_proto_goTypes = []any{
	(*AnomalyReportRequest)(nil),  // 0: cortex.telemetry.v1.AnomalyReportRequest
	(*AnomalyReportResponse)(nil), // 1: cortex.telemetry.v1.AnomalyReportResponse
}
var file_api_proto_v1_telemetry_proto_depIdxs = []int32{
	0, // 0: cortex.telemetry.v1.TelemetryService.ReportAnomaly:input_type -> cortex.telemetry.v1.AnomalyReportRequest
	1, // 1: cortex.telemetry.v1.TelemetryService.ReportAnomaly:output_type -> cortex.telemetry.v1.AnomalyReportResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_telemetry_proto_init() }
func file_api_proto_v1_telemetry_proto_init() {
	if File_api_proto_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_telemetry_proto_rawDesc), len(file_api_proto_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_telemetry_proto_msgTypes,
	}.Build()
	File_api_proto_v1_telemetry_proto = out.File
	file_api_proto_v1_telemetry_proto_goTypes = nil
	file_api_proto_v1_telemetry_proto_depIdxs = nil
}
